<section>
<div class="linha">
<div class="coluna col12">
	<div class="coluna col6">
		<figure class="foto-legenda">
			<img src="img/tela_regras_cadastro.jpg">
		</figure>
	</div>	
	<div class="coluna col11">
		<h1>Regras</h1>

		<h2>Regras são parametrizações tanto para lojas como para Reaguarda.</h2>
<p>REGRA DE ENTRADA DE NOTAS</p>
<p>EXIGIR CLIENTE NA VENDA</p>
<p>PRÉ-VENDA</p>
<p>BLOQUEAR DESCONTO PROGRESSIVO NA RETIRADA</p>
<p>PERMITIR VENCIMENTO FORA EXPEDIENTE BANCARIO</p>
<p>IMPRIMIR VENDEDOR NO CUPOM</p>
<p>CALCULAR JUROS COM 30 DIAS</p>
<p>EXIBIR ABA PARA ATUALIZAR PREÇOS</p>
<p>ICMS PARTILHADO</p>
<p>TOTALIZAR PEÇAS DE PRÉ-VENDA</p>
<p>EXIBIR FORNECEDOR PELA RAZAO SOCIAL</p>
<p>NÃO ATUALIZAR PREÇO DE CUSTO NA ENTRADA DE NOTAS</p>
<p>NÃO MARCAR OPÇÃO DE ENVIAR NOTA DE DEVOLUÇÃO</p>
<p>HABILITAR UTILIZAÇÃO DE LEITOR BIOMETRICO</p>
<p>IMPRIMIR CUPOM DE TROCA DE MERCADORIA</p>
<p>HABILITAR DESCONTO/ACRESCIMO POR ITEM NA VENDA</p>
<p>RATEAR VALORES ADICIONAIS NOS ITENS DA NOTA</p>
<p>HABILITAR BOTÃO DE PRÉ-VENDA</p>
<p>DESABILITAR BOTÃO DE TROCA</p>
<p>DESABILITAR BOTÃO DE VENDA DE VALE</p>
<p>RETIRAR REFERENCIA DA DESCRIÇÃO</p>
<p>HABILITAR REFERENCIAS SEQUENCIAIS ENTRE REDES</p>
<p>HABILITAR UTILIZAÇÃO DE BALANÇA</p>
<p>HABILITAR NOVA TELA DE CADASTRO DE NOTA FISCAL</p>
<p>IMPORTAR PEDIDO DE ENTREGA</p>
<p>EMISSÃO DE NOTA PROMISSÓRIA NO FINAL DA VENDA</p>
<p>EMISSÃO DO CARNÊ DE CREDIÁRIO NO FINAL DA VENDA</p>
<p>EDITAR PRE-VENDA AO RESTAURAR</p>
<p>EMITE CUPOM DE TROCA</p>
<p>GERAR DISTRIBUICAO DO ROMANEIO</p>
<p>HABILITAR EMISSÃO DE NF-E NA TRANSFERENCIA</p>
<p>HABILITAR ENVIO AUTOMATICO DE TRANSFERENCIA</p>
<p>HABILITA PLANO DE PAGAMENTO PARA VENDAS</p>
<p>HABILITAR PROGRAMA DE BONUS</p>
<p>CLIENTE GERA SPED</p>
<p>ENVIAR XML PARA CONTADOR</p>
<p>NÃO ABATE ESTOQUE NA VENDA</p>
<p>HABILITAR ENTRADA DE NOTAS POR CONVERSAO DE CFOP</p>
<p>HABILITA DIGITAÇÃO NA RESTAURAÇÃO DA PRÉ-VENDA</p>
<p>SEPARAR RELATÓRIOS POR CAIXA</p>
<p>HABILITAR DESCONTOS POR ITEM NA PRE-VENDA</p>
<p>EXPORTAR DATA DE ATUALIZAÇÃO DO ESTOQUE</p>
<p>TRAVAR PRODUTO SEM CUSTO NA VENDA</p>
<p>NÃO PERMITIR ENTRADA DE NOTAS NA MATRIZ FRANQUIA</p>
<p>HABILITAR QTD NA PESQUISA DE PRODUTOS NA VENDA</p>
<p>SELECIONAR TIPO DE NFE NA VENDA</p>
<p>TRABALHA COM AUTORIZAÇÃO NO PEDIDO DE COMPRA</p>
<p>TRABALHA COM ESTOQUE RESERVADO</p>
<p>BLOQUEAR DESCONTO EM PRODUTOS COM PROMOÇÃO</p>
<p>DESABILITAR MENSAGEM NO FIM DA VENDA</p>
<p>HABILITAR INATIVAÇÃO DE PRODUTOS COM SALDO</p>
<p>USAR LAYOUT ESPECÍFICO PARA CLIENTE NA VENDA</p>
<p>ALTERAR VENCIMENTO DUPLICATA/CREDIARIO</p>
<p>HABILITAR DESCONTO GERAL NA PRE-VENDA</p>
<p>FECHAMENTO AS CEGAS</p>
<p>HABILITAR NFE 4.00</p>
<p>INCLUSÃO DE TRANSFERENCIA SOMENTE POR ACEITE</p>
<p>TIPO DESCONTO POR USUARIO</p>
<p>REQUISIÇÃO DE PRODUTOS SOMENTE COM SALDO</p>
<p>EXIBIR MARCKUP NO MOMENTO DA VENDA</p>
<p>GERAR TRANSFERÊNCIA PÓS DEVOLUÇÃO</p>
<p>FORÇAR FECHAMENTO DE CAIXA</p>
<p>ATIVAR RFID</p>
<p>VALOR DE VALE ABATE DO TOTAL DE VENDAS</p>
<p>DISTRIBUIÇÃO ALTERA ESTOQUE APÓS RECEBIMENTO</p>
<p>NÃO INSERIR SERVIÇOS NA NFC-E</p>
<p>IMPRIMIR RESUMO NA VENDA</p>
<p>SEPARAR NFCE POR FORNECEDOR</p>
<p>CONSULTAR ITENS DE VENDA VIA WEBSERVICE</p>
<p>EXPORTAR SALDOS PARA A MATRIZ FRANQUIA</p>
<p>CONTROLE DE SALDO DO CAIXA</p>
<p>OPTAR TIPO DE VENDA</p>
<p>HABILITAR EXCLUSÃO GERENCIAL DE VENDA NFCE</p>
<p>DESATIVAR CAIXA AS CEGAS EM MOVIMENTOS FINALIZADOS</p>
<p>CONSIDERAR CONFIG. FECHAMENTO DE PREVENDA PARA ECF</p>
<p>INCLUIR/ALTERAR VENDEDORES SÓ NA FRANQUEADORA</p>
<p>HABILITAR CATEGORIA NA REFERÊNCIA</p>
<p>OUTROS SOMENTE COM RETIRADA FUNCIONÁRIO</p>
<p>HABILITA CONFERENCIA DE PREVENDA</p>
<p>DESABILITAR SOMA DO CAIXA/DESPESA COM O DINHEIRO</p>
<p>RELATÓRIO VENDA PRODUTOS MOVIMENTO ANTERIOR</p>
<p>TRABALHA SOMENTE COM PLANOS DE PAGAMENTO VISIVEIS</p>
<p>EXCLUIR VARIOS ITENS NA VENDA</p>
<p>NÃO GERAR NFE DE DEVOLUÇÃO A PARTIR DE NOTA MANUAL</p>
<p>NÃO GERAR BÔNUS APLICANDO DESCONTO MANUAL.</p>
<p>GERAR BÔNUS PARA PRODUTOS FORA DE PROMOÇÃO</p>
<p>UTILIZA DEPENDENTES NO CADASTRO DE CLIENTE</p>
<p>LOGO DA REDE A PARTIR DO DIRETÓRIO DE FOTOS</p>
<p>PERGUNTAR SE DESEJA IMPRIMIR CUPOM DE NFC-E</p>
<p>TRABALHA COM CONFERÊNCIA DE PEDIDO DE VENDA</p>
<p>NÃO ARMAZENAR HISTÓRICO DE PREÇO</p>
<p>INFORMAR O PRODUTO NEGATIVO NA VENDA</p>
<p>TRAB. COM REQUISIÇÃO DE PED. DE COMPRA</p>
<p>VERIFICAR PARCELA NA BAIXA DE CREDIÁRIO</p>
<p>TRABALHA COM PROMOÇÃO SELLBIE</p>
<p>PEDIDO DE ENTREGA NA TELA DE VENDAS</p>
<p>HABILITAR CLASSIFICAÇÃO DE CLIENTE</p>
<p>ANALISE DE PEDIDO COM FILIAL CENTRALIZADA</p>
<p>NÃO ENVIAR CPF NA NFCE</p>
<p>NÃO SEPARAR ITENS NA PROMOÇÃO PARA VÁRIAS PEÇAS</p>
<p>TRABALHA COM CUSTOMIZACAO DE CAMISAS</p>
<p>HABILITA FILIAÇÃO NO CADASTRO DE CLIENTE</p>
<p>GERAR NOTA PELO DOC DA VENDA SÓ COM VALOR LÍQUIDO</p>
<p>LOJA VISUALIZA SOMENTE SUAS COMPRAS NO CLIENTE</p>
<p>HABILITAR Nº DA NOTA NA VENDA POR NOTA MANUAL</p>
<p>TRABALHA COM INTEGRAÇÃO LUXOTTICA</p>
<p>TRABALHA COM DELIVERY</p>
<p>ENVIAR ENDEREÇO DO DESTINATÁRIO NA NFCE</p>
<p>INFORMAR QUANTIDADE DE PARCELAS DO CHEQUE NA VENDA</p>
<p>BLOQUEAR FUNÇÃO F3</p>
<p>	TRABALHA COM OUTROS TIPOS DE ESTOQUE PADRÃO</p>
<p>	TRABALHA COM ESTOQUE RESERVADO PEDIDO DE VENDA</p>
<p>	TRABALHA COM INTEGRAÇÃO COM TRANSPORTADORAS</p>
<p>	HABILITAR CONTIGENCIA OFFLINE</p>
<p>	VENDEDOR POR ITEM DA VENDA</p>
	</div>
</div>
</div>
</section>