<section>
<div class="linha">
<div class="coluna col12">
	<div class="coluna col6">
		<figure class="foto-legenda">
			<img src="img/tela_regras_cadastro.jpg">
		</figure>
	</div>	
	<div class="coluna col11">
		<h1>Regras</h1>

		<h2>Regras são parametrizações tanto para lojas como para Reaguarda.</h2>
		<table id="tabelaspec">
<!--<tr><td class="ce">REGRA DE ENTRADA DE NOTAS</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">EXIGIR CLIENTE NA VENDA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">PRÉ-VENDA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">BLOQUEAR DESCONTO PROGRESSIVO NA RETIRADA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">PERMITIR VENCIMENTO FORA EXPEDIENTE BANCARIO</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">IMPRIMIR VENDEDOR NO CUPOM</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">CALCULAR JUROS COM 30 DIAS</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">EXIBIR ABA PARA ATUALIZAR PREÇOS</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">ICMS PARTILHADO</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">TOTALIZAR PEÇAS DE PRÉ-VENDA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">EXIBIR FORNECEDOR PELA RAZAO SOCIAL</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">NÃO ATUALIZAR PREÇO DE CUSTO NA ENTRADA DE NOTAS</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">NÃO MARCAR OPÇÃO DE ENVIAR NOTA DE DEVOLUÇÃO</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">HABILITAR UTILIZAÇÃO DE LEITOR BIOMETRICO</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">IMPRIMIR CUPOM DE TROCA DE MERCADORIA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">HABILITAR DESCONTO/ACRESCIMO POR ITEM NA VENDA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">RATEAR VALORES ADICIONAIS NOS ITENS DA NOTA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">HABILITAR BOTÃO DE PRÉ-VENDA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">DESABILITAR BOTÃO DE TROCA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">DESABILITAR BOTÃO DE VENDA DE VALE</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">RETIRAR REFERENCIA DA DESCRIÇÃO</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">HABILITAR REFERENCIAS SEQUENCIAIS ENTRE REDES</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">HABILITAR UTILIZAÇÃO DE BALANÇA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">HABILITAR NOVA TELA DE CADASTRO DE NOTA FISCAL</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">IMPORTAR PEDIDO DE ENTREGA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">EMISSÃO DE NOTA PROMISSÓRIA NO FINAL DA VENDA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">EMISSÃO DO CARNÊ DE CREDIÁRIO NO FINAL DA VENDA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">EDITAR PRE-VENDA AO RESTAURAR</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">EMITE CUPOM DE TROCA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">GERAR DISTRIBUICAO DO ROMANEIO</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">HABILITAR EMISSÃO DE NF-E NA TRANSFERENCIA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">HABILITAR ENVIO AUTOMATICO DE TRANSFERENCIA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">HABILITA PLANO DE PAGAMENTO PARA VENDAS</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">HABILITAR PROGRAMA DE BONUS</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">CLIENTE GERA SPED</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">ENVIAR XML PARA CONTADOR</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">NÃO ABATE ESTOQUE NA VENDA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">HABILITAR ENTRADA DE NOTAS POR CONVERSAO DE CFOP</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">HABILITA DIGITAÇÃO NA RESTAURAÇÃO DA PRÉ-VENDA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">SEPARAR RELATÓRIOS POR CAIXA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">HABILITAR DESCONTOS POR ITEM NA PRE-VENDA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">EXPORTAR DATA DE ATUALIZAÇÃO DO ESTOQUE</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">TRAVAR PRODUTO SEM CUSTO NA VENDA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">NÃO PERMITIR ENTRADA DE NOTAS NA MATRIZ FRANQUIA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">HABILITAR QTD NA PESQUISA DE PRODUTOS NA VENDA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">SELECIONAR TIPO DE NFE NA VENDA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">TRABALHA COM AUTORIZAÇÃO NO PEDIDO DE COMPRA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">TRABALHA COM ESTOQUE RESERVADO</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">BLOQUEAR DESCONTO EM PRODUTOS COM PROMOÇÃO</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">DESABILITAR MENSAGEM NO FIM DA VENDA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">HABILITAR INATIVAÇÃO DE PRODUTOS COM SALDO</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">USAR LAYOUT ESPECÍFICO PARA CLIENTE NA VENDA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">ALTERAR VENCIMENTO DUPLICATA/CREDIARIO</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">HABILITAR DESCONTO GERAL NA PRE-VENDA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">FECHAMENTO AS CEGAS</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">HABILITAR NFE 4.00</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">INCLUSÃO DE TRANSFERENCIA SOMENTE POR ACEITE</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">TIPO DESCONTO POR USUARIO</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">REQUISIÇÃO DE PRODUTOS SOMENTE COM SALDO</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">EXIBIR MARCKUP NO MOMENTO DA VENDA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">GERAR TRANSFERÊNCIA PÓS DEVOLUÇÃO</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">FORÇAR FECHAMENTO DE CAIXA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">ATIVAR RFID</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">VALOR DE VALE ABATE DO TOTAL DE VENDAS</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">DISTRIBUIÇÃO ALTERA ESTOQUE APÓS RECEBIMENTO</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">NÃO INSERIR SERVIÇOS NA NFC-E</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">IMPRIMIR RESUMO NA VENDA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">SEPARAR NFCE POR FORNECEDOR</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">CONSULTAR ITENS DE VENDA VIA WEBSERVICE</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">EXPORTAR SALDOS PARA A MATRIZ FRANQUIA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">CONTROLE DE SALDO DO CAIXA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">OPTAR TIPO DE VENDA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">HABILITAR EXCLUSÃO GERENCIAL DE VENDA NFCE</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">DESATIVAR CAIXA AS CEGAS EM MOVIMENTOS FINALIZADOS</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">CONSIDERAR CONFIG. FECHAMENTO DE PREVENDA PARA ECF</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">INCLUIR/ALTERAR VENDEDORES SÓ NA FRANQUEADORA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">HABILITAR CATEGORIA NA REFERÊNCIA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">OUTROS SOMENTE COM RETIRADA FUNCIONÁRIO</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">HABILITA CONFERENCIA DE PREVENDA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">DESABILITAR SOMA DO CAIXA/DESPESA COM O DINHEIRO</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">RELATÓRIO VENDA PRODUTOS MOVIMENTO ANTERIOR</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">TRABALHA SOMENTE COM PLANOS DE PAGAMENTO VISIVEIS</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">EXCLUIR VARIOS ITENS NA VENDA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">NÃO GERAR NFE DE DEVOLUÇÃO A PARTIR DE NOTA MANUAL</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">NÃO GERAR BÔNUS APLICANDO DESCONTO MANUAL.</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">GERAR BÔNUS PARA PRODUTOS FORA DE PROMOÇÃO</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">UTILIZA DEPENDENTES NO CADASTRO DE CLIENTE</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">LOGO DA REDE A PARTIR DO DIRETÓRIO DE FOTOS</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">PERGUNTAR SE DESEJA IMPRIMIR CUPOM DE NFC-E</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">TRABALHA COM CONFERÊNCIA DE PEDIDO DE VENDA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">NÃO ARMAZENAR HISTÓRICO DE PREÇO</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">INFORMAR O PRODUTO NEGATIVO NA VENDA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">TRAB. COM REQUISIÇÃO DE PED. DE COMPRA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">VERIFICAR PARCELA NA BAIXA DE CREDIÁRIO</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">TRABALHA COM PROMOÇÃO SELLBIE</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">PEDIDO DE ENTREGA NA TELA DE VENDAS</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">HABILITAR CLASSIFICAÇÃO DE CLIENTE</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">ANALISE DE PEDIDO COM FILIAL CENTRALIZADA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">NÃO ENVIAR CPF NA NFCE</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">NÃO SEPARAR ITENS NA PROMOÇÃO PARA VÁRIAS PEÇAS</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">TRABALHA COM CUSTOMIZACAO DE CAMISAS</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">HABILITA FILIAÇÃO NO CADASTRO DE CLIENTE</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">GERAR NOTA PELO DOC DA VENDA SÓ COM VALOR LÍQUIDO</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">LOJA VISUALIZA SOMENTE SUAS COMPRAS NO CLIENTE</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">HABILITAR Nº DA NOTA NA VENDA POR NOTA MANUAL</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">TRABALHA COM INTEGRAÇÃO LUXOTTICA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">TRABALHA COM DELIVERY</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">ENVIAR ENDEREÇO DO DESTINATÁRIO NA NFCE</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">INFORMAR QUANTIDADE DE PARCELAS DO CHEQUE NA VENDA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">BLOQUEAR FUNÇÃO F3</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">	TRABALHA COM OUTROS TIPOS DE ESTOQUE PADRÃO</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">	TRABALHA COM ESTOQUE RESERVADO PEDIDO DE VENDA</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">	TRABALHA COM INTEGRAÇÃO COM TRANSPORTADORAS</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">	HABILITAR CONTIGENCIA OFFLINE</td><td class="cd">DESCRICAO</td></tr>
<tr><td class="ce">	VENDEDOR POR ITEM DA VENDA</td><td class="cd">DESCRICAO</td></tr>-->
<tr><td class="ce">REGRA DE ENTRADA DE NOTAS</td><td class="cd">DATA DE ENTREGA DO PEDIDO MENOR QUE A DATA DE ENTRADA DA NOTA</td></tr>
<tr><td class="ce">EXIGIR CLIENTE NA VENDA</td><td class="cd">ALERTAR = NÃO EXIGE O CLIENTE NA VENDA, BLOQUEAR = OBRIGA O CLIENTE NA VENDA</td></tr>
<tr><td class="ce">PRÉ-VENDA</td><td class="cd">AO HABILITAR, PERMITE A RESTAURAÇÃO DE PRÉ-VENDA, PORÉM PRECISA ESTAR HABILITADA A REGRA 18</td></tr>
<tr><td class="ce">BLOQUEAR DESCONTO PROGRESSIVO NA RETIRADA</td><td class="cd">BLOQUEIA O DESCONTO PROGRESSIVO QUANDO A RETIRADA DE FUNCIONÁRIO ESTÁ SELECIONADA. </td></tr>
<tr><td class="ce">PERMITIR VENCIMENTO FORA EXPEDIENTE BANCARIO</td><td class="cd">AO HABILIATAR A REGRA, O SISTEMA POSSIBILITA INFORMAR O VENCIMENTO DO PAGAMENTO FORA DO EXPEDIENTE BANCARIO. O USUARIO SÓ PODE USAR O "SABADO", COMO DIA DA SEMANA DESSE "FORA DO EXPEDIENTE BANCARIO". DOMINGOS E FERIADOS NACIONAIS NÃO FUNCIONAM NESSA REGRA</td></tr>
<tr><td class="ce">IMPRIMIR VENDEDOR NO CUPOM</td><td class="cd">COM ESSA REGRA HABILIATA, O SISTEMA INFORMA O NOME DO VENDEDOR NO CUPOM FISCAL (ECF). SOMENTE EM IMPRESSORAS ECF.</td></tr>
<tr><td class="ce">CALCULAR JUROS COM 30 DIAS</td><td class="cd">AO HABILITAR A REGRA, O SISTEMA COMEÇA A CALCULAR OS JUROS DAS PARCELAS EM ATRASOS DOS CREDIÁRIOS, APARTIR DE 30 DIAS APOS O VENCIMENTO.</td></tr>
<tr><td class="ce">EXIBIR ABA PARA ATUALIZAR PREÇOS</td><td class="cd">REGRA HABILITA ABA NA TELA ENTRADA DE NOTAS, POSSIBILITANDO ALTERAR O PREÇO DE VENDA DAS MERCADORIAS INSERIDAS NA ENTRADA DE NOTAS.</td></tr>
<tr><td class="ce">ICMS PARTILHADO</td><td class="cd">HABILITA O CALCULO DO DIFAL, QUE CONDIZ A DIFERENÇA DE ALIQUOTA DA VENDA DE UM ESTADO PARA OUTRO</td></tr>
<tr><td class="ce">TOTALIZAR PEÇAS DE PRÉ-VENDA</td><td class="cd">HABILITANDO A REGRA, AO UTILIZAR O F3 PESQUISAR PRODUTO, MOSTRA UMA COLUNA ONDE PODE SER DIGITADA A QTD DO ITEM</td></tr>
<tr><td class="ce">EXIBIR FORNECEDOR PELA RAZAO SOCIAL</td><td class="cd">HABILITANDO A REGRA, O SISTEMA MOSTRA A RAZAO SOCIAL EM VEZ DE NOME FANTASIA NO CAMPO FORNECEDOR NO CADASTRO DE PRODUTO.</td></tr>
<tr><td class="ce">NÃO ATUALIZAR PREÇO DE CUSTO NA ENTRADA DE NOTAS</td><td class="cd">ATIVADO NÃO ALTERA A TABELA CONTABIL, DESATIVADO CARREGA O VALOR TOTAL DO ITEM DA NOTA NA TABELA CONTABIL.</td></tr>
<tr><td class="ce">NÃO MARCAR OPÇÃO DE ENVIAR NOTA DE DEVOLUÇÃO</td><td class="cd">AO ATIVAR, A OPÇÃO DE "EMITIR NOTA DE DEVOLUÇÃO" IRÁ SER DESMARCADA, QUANDO ESTIVER FAZENDO UMA TROCA NA TELA DE VENDA. O SISTEMA NAO VAI GERAR E ENVIAR A NFE DE ENTRADA.</td></tr>
<tr><td class="ce">HABILITAR UTILIZAÇÃO DE LEITOR BIOMETRICO</td><td class="cd">USUARIO PODE ACESSAR O SISTEMA ATRAVÉS DO LEITOR BIOMETRICO CONECTADO NO COMPUTADOR, SEM A NECESSIDADE DE INFORMAR O USUARIO E SENHA.</td></tr>
<tr><td class="ce">IMPRIMIR CUPOM DE TROCA DE MERCADORIA</td><td class="cd">IRÁ IMPRIMIR UM COMPROVANTE DE TROCA NO FINAL DA VENDA, PARA CADA PRODUTO LANÇADO NE VENDA ESPECIFICA.</td></tr>
<tr><td class="ce">HABILITAR DESCONTO/ACRESCIMO POR ITEM NA VENDA</td><td class="cd">HABILITA CAMPO DE DESCONTO/ACRÉSCIMO NA TELA DE VENDAS, PARA CADA ITEM LANÇADO NA TELA.</td></tr>
<tr><td class="ce">RATEAR VALORES ADICIONAIS NOS ITENS DA NOTA</td><td class="cd">TESTEI E NÃO IDENTIFIQUEI (FEITO A ENTRADA DE NOTAS POREM O CAMPO DE VALORES ADICIONAIS NAO FOI IDENTIFICADO)</td></tr>
<tr><td class="ce">HABILITAR BOTÃO DE PRÉ-VENDA</td><td class="cd">SERÁ HABILITADO BOTÃO “F2 (RESTAURAR PRÉ VENDA)” EM QUALQUER TELA DE VENDA .</td></tr>
<tr><td class="ce">DESABILITAR BOTÃO DE TROCA</td><td class="cd">AO ATIVAR, O ATALHO F6 “TROCAS”, SERÁ REMOVIDO DA TELA DE VENDAS.</td></tr>
<tr><td class="ce">DESABILITAR BOTÃO DE VENDA DE VALE</td><td class="cd">AO ATIVAR, O ATALHO F11 “VENDA DE VALE” SERÁ REMOVIDO DA TELA DE VENDAS.</td></tr>
<tr><td class="ce">RETIRAR REFERENCIA DA DESCRIÇÃO</td><td class="cd">AO HABILITAR ESSA REGRA, O SISTEMA TIRA DA DESCRIÇÃO A REFERENCIA NO MOMENTO DA VENDA (AO LISTAR).</td></tr>
<tr><td class="ce">HABILITAR REFERENCIAS SEQUENCIAIS ENTRE REDES</td><td class="cd">AO HABILITAR, O SISTEMA SEGUE UMA ORDEM SEQUENCIAL DE CRIAÇÃO DAS REFERENCIAS PARA CADA REDE INDIVIDUALMENTE (OBS: VERIFICAR O CAMPO “ULTIMA REFERENCIA”)</td></tr>
<tr><td class="ce">HABILITAR UTILIZAÇÃO DE BALANÇA</td><td class="cd">HABILITA O SISTEMA PARA UTILIZAR BALANÇA DE PESO CONECTADA A MAQUINA QUE UTILIZA O SISTEMA DA PDVNET.</td></tr>
<tr><td class="ce">HABILITAR NOVA TELA DE CADASTRO DE NOTA FISCAL</td><td class="cd">AO HABILITAR ESSA REGRA SERA NECESSARIO CRIAR UM LAYOUT NA CONFIGURAÇÃO DE LAYOUT. APOS ISSO, ESSE CADASTRO NOVO APARECE NA TELA DE VENDA, AO FINALIZAR A VENDA.</td></tr>
<tr><td class="ce">IMPORTAR PEDIDO DE ENTREGA</td><td class="cd">IMPORTAR OS PEDIDOS DE ENTREGA</td></tr>
<tr><td class="ce">EMISSÃO DE NOTA PROMISSÓRIA NO FINAL DA VENDA</td><td class="cd">AS NOTAS PROMISSÓRIAS COM AS QUANTIDADES DE CADA PARCELA INFORMADA NA FORMA DE PAGAMENTO CREDIARIO, SERÃO IMPRESSAS AO FINALIZAR A VENDA. </td></tr>
<tr><td class="ce">EMISSÃO DO CARNÊ DE CREDIÁRIO NO FINAL DA VENDA</td><td class="cd">OS COMPROVANTES DE CADA PARCELA DO CARNE, SERÃO IMPRESSOS AO FINALIZAR A VENDA NO CREDIÁRIO.</td></tr>
<tr><td class="ce">EDITAR PRE-VENDA AO RESTAURAR</td><td class="cd">AO ATIVAR, SERÁ PERMITIDO EDITAR A PRÉ-VENDA NA TELA DE VENDAS  AO RESTAURAR A "PRE-VENDA" PELO "F2".</td></tr>
<tr><td class="ce">EMITE CUPOM DE TROCA</td><td class="cd">QUANDO FINALIZAR A VENDA, EMITE CUPOM DE TROCA POR ITEM.</td></tr>
<tr><td class="ce">GERAR DISTRIBUICAO DO ROMANEIO</td><td class="cd">REGRA SERVE PARA PERMITIR QUE A MATRIZ POSSA GERAR A DISTRIBUIÇÃO UTILIZANDO O ROMANEIO DO REMANEJAMENTO FEITO NO PDVANALISE.</td></tr>
<tr><td class="ce">HABILITAR EMISSÃO DE NF-E NA TRANSFERENCIA</td><td class="cd">AO INCLUIR UMA TRANSFERENCIA O SISTEMA GERA E PERGUNTA SE DESEJA ENVIAR A NFE AUTOMATICAMENTE.  A SÉRIE DE NOTA , A NATUREZA DE OPERAÇÃO E O CST/CSOSN PADRÃO PARA AS NOTAS GERADAS, DEVERÃO SER INCLUÍDAS NO CADASTRO DA FILIAL NO SISTEMA.</td></tr>
<tr><td class="ce">HABILITAR ENVIO AUTOMATICO DE TRANSFERENCIA</td><td class="cd">AO FINALIZAR O CADASTRO DA TRANSFERENCIA, O SISTEMA ENVIA OS DADOS LANCADOS DESSA TRANSFERENCIA PARA A RETAGUARDA E A LOJA DE DESTINO.</td></tr>
<tr><td class="ce">HABILITA PLANO DE PAGAMENTO PARA VENDAS</td><td class="cd">HABILITA A NOVA FORMA DE PAGAMENTO NA TELA DE VENDAS. ESSAS FORMAS DE PAGAMENTOS DEVEM SER CRIADAS E CONFIGURADAS NA RETAGUARDA. SERÁ PRECISO HABILITAR A REGRA 82, PARA AS OPÇÕES SEREM VISÍVEIS NA TELA DE VENDAS.</td></tr>
<tr><td class="ce">HABILITAR PROGRAMA DE BONUS</td><td class="cd">HBILITA SISTEMA DE BONUS NO SISTEMA (SISTEMA ANTIGO DE BONUS)</td></tr>
<tr><td class="ce">CLIENTE GERA SPED</td><td class="cd">TESTEI E NÃO IDENTIFIQUEI (FOI POSSIVEL GERAR SPED MESMO SEM A REGRA ATIVADA)</td></tr>
<tr><td class="ce">ENVIAR XML PARA CONTADOR</td><td class="cd">HABILITANDO A REGRA, PERMITE O SISTEMA ENIVAR O XML DE CADA VENDA FEITA PELA TELA DE NFCE, PARA O EMAIL DO CONTADOR.PARA QUE ISSO FUNCIONE, É PRECISO CONFIGURAR O EMAIL DISPARADOR NO SISTEMA E CADASTRAR O CONTADOR TAMBEM NO SISTEMA. A CADA VENDA FEITA O CONTADOR RECEBERÁ O XML EM SEU EMAIL.</td></tr>
<tr><td class="ce">NÃO ABATE ESTOQUE NA VENDA</td><td class="cd">AO ATIVAR, APÓS REALIZAR VENDAS, NÃO SERÁ ALTERADO O SALDO DOS PRODUTOS VENDIDOS.</td></tr>
<tr><td class="ce">HABILITAR ENTRADA DE NOTAS POR CONVERSAO DE CFOP</td><td class="cd">HABILITA O SISTEMA PARA CONVERTER NOTAS DE SAIDA PARA DAR ENTRADA</td></tr>
<tr><td class="ce">HABILITA DIGITAÇÃO NA RESTAURAÇÃO DA PRÉ-VENDA</td><td class="cd">AO ATIVAR, SERÁ PERMITIDO INCLUIR PRODUTOS APÓS RESTAURAR UMA PRÉ-VENDA NA TELA DE VENDAS.</td></tr>
<tr><td class="ce">SEPARAR RELATÓRIOS POR CAIXA</td><td class="cd">RELATÓRIOS SERÃO DIVIDIDOS POR CAIXA.</td></tr>
<tr><td class="ce">HABILITAR DESCONTOS POR ITEM NA PRE-VENDA</td><td class="cd">HABILITA A FORMA DE DESCONTO POR ITEM NO PDVPREVENDA.</td></tr>
<tr><td class="ce">EXPORTAR DATA DE ATUALIZAÇÃO DO ESTOQUE</td><td class="cd">HABILITA A EXPORTACAO NO PDVSYNC  DA DATA DE ATUALIZACAO DO SALDO DO ESTOQUE, PARA QUE O PDVINTEGRADOR ESTIVER CONFIGURADO NA LOJA, CONSIGA VER A DATA E SUBIR QUANDO O SALDO FOR ALTERADO</td></tr>
<tr><td class="ce">TRAVAR PRODUTO SEM CUSTO NA VENDA</td><td class="cd">TRAVA A VENDA DE PRODUTOS SEM CUSTO NA TELA DE VENDAS.</td></tr>
<tr><td class="ce">NÃO PERMITIR ENTRADA DE NOTAS NA MATRIZ FRANQUIA</td><td class="cd">HABILITANDO ESSA REGRA, A MATRIZ FRANQUIA FICA IMPOSSIBILITADA DE ENTRAR COM AS NOTAS PELO SISTEMA DE RETAGUARDA. SO A LOJA DA FRANQUIA QUE CONSEGUE ENTRAR COM AS NOTAS.</td></tr>
<tr><td class="ce">HABILITAR QTD NA PESQUISA DE PRODUTOS NA VENDA</td><td class="cd">HABILITA A COLUNA QUANTIDADE QUANDO APERTA O "F3" AO PESQUISAR PRODUTOS DURANTE UMA VENDA.</td></tr>
<tr><td class="ce">SELECIONAR TIPO DE NFE NA VENDA</td><td class="cd">PERMITE ESCOLHER SE IRÁ UTILIZAR NFe OU NFC-e QUANDO ABERTO A TELA DE NFCE.</td></tr>
<tr><td class="ce">TRABALHA COM AUTORIZAÇÃO NO PEDIDO DE COMPRA</td><td class="cd">REGRA PERMITE QUE O PEDIDO DE COMPRA  SEJA AUTORIZADO NO PDVESTOQUE LOGO ASSIM QUE É CRIADO. IRA APARECER UM  BOTAO "AUTORIZAR" NA TELA DE PESQUISA DO PEDIDO DE COMPRA, PARA AUTORIZAR. (Utilizado em modelo 1 - Autorização configurada por usuário.)</td></tr>
<tr><td class="ce">TRABALHA COM ESTOQUE RESERVADO</td><td class="cd">PERMITE RESERVAR O ESTOQUE DE DETERMINADO PRODUTO PARA A FILIAL REQUISITADA (FUNCIONA APENAS COM BANCO EM NUVEM DE MATRIZ E LOJA UNIFICADOS)</td></tr>
<tr><td class="ce">BLOQUEAR DESCONTO EM PRODUTOS COM PROMOÇÃO</td><td class="cd">BLOQUEIA O DESCONTO POR ITEM  NOS PRODUTOS QUE ESTÃO EM  PROMOÇÃO.</td></tr>
<tr><td class="ce">DESABILITAR MENSAGEM NO FIM DA VENDA</td><td class="cd">DESABILITA CAIXA DE MENSAGEM COM NUMERO DA VENDA NO FINAL DA VENDA.</td></tr>
<tr><td class="ce">HABILITAR INATIVAÇÃO DE PRODUTOS COM SALDO</td><td class="cd">AO ATIVAR,SERÁ PERMITIDO A INATIVAÇÃO DO PRODUTO COM SALDO, DENTRO DO CADASTRO DE PRODUTO, NA ABA CODIGO DE BARRA OU NA PROPRIA REFERENCIA.</td></tr>
<tr><td class="ce">USAR LAYOUT ESPECÍFICO PARA CLIENTE NA VENDA</td><td class="cd">REGRA PERMITE, USAR UM LAYOUT NOVO E COM CAMPOS ESPECIFICOS PARA O CADASTRO DO CLIENTE NA TELA DE VENDAS. O CADASTRO DO LAYOUT FICA NO "RETAGUARDA", ABA CLIENTES, CONFIGURAÇÃO DE LAYOUT. </td></tr>
<tr><td class="ce">ALTERAR VENCIMENTO DUPLICATA/CREDIARIO</td><td class="cd">ALTERAR DATA DE VENCIMENTO DO CREDIÁRIO/DUPLICATA, QUANTO A REGRA 33 ESTIVER HABILITADA.</td></tr>
<tr><td class="ce">HABILITAR DESCONTO GERAL NA PRE-VENDA</td><td class="cd">HABILITA O CAMPO DESCONTO, PARA QUE O MESMO POSSA SER UTILIZADO NA CRIAÇÃO DA PRE VENDA</td></tr>
<tr><td class="ce">FECHAMENTO AS CEGAS</td><td class="cd">HABILITA O FECHAMENTO DO MOVIMENTO BLOQUEANDO O ACESSO AOS RELATÓRIOS DE FECHAMENTO E OBRIGANDO A DIGITAÇÃO DOS VALORES DO CAIXA.</td></tr>
<tr><td class="ce">HABILITAR NFE 4.00</td><td class="cd">HABILITA A UTILIZAÇÃO DA VERSÃO 4.00 DA NFE/NFCE.</td></tr>
<tr><td class="ce">INCLUSÃO DE TRANSFERENCIA SOMENTE POR ACEITE</td><td class="cd">A INCLUSÃO DE TRANSFERENCIAS DE ENTRADA SERÃO FEITAS SOMENTE A PARTIR DAS TRANSFERÊNCIAS DE ENTRADA SEM CONFIRMAÇÃO.</td></tr>
<tr><td class="ce">TIPO DESCONTO POR USUARIO</td><td class="cd">NO CADASTRO DE USUÁRIO HABILITA O CAMPO “TIPO DESCONTO” NO NOTAO ‘CLASSIFICADORES’, LIBERANDO SOMENTE OS DESCONTOS RELATIVO AO USUARIO.</td></tr>
<tr><td class="ce">REQUISIÇÃO DE PRODUTOS SOMENTE COM SALDO</td><td class="cd">NO CADASTRO DE USUÁRIO HABILITA O CAMPO “TIPO DESCONTO” NO NOTAO ‘CLASSIFICADORES’, LIBERANDO SOMENTE OS DESCONTOS RELATIVO AO USUARIO.</td></tr>
<tr><td class="ce">EXIBIR MARCKUP NO MOMENTO DA VENDA</td><td class="cd">APRESENTA O MARKUP DO PRODUTO NA TELA DE VENDA ABAIXO DO CAMPO ‘PRODUTO’.</td></tr>
<tr><td class="ce">GERAR TRANSFERÊNCIA PÓS DEVOLUÇÃO</td><td class="cd">AO FINALIZAR A TROCA, O SISTEMA GERA UMA TRANSFERÊNCIA DAS PEÇAS RELACIONADAS NA TROCA AUTOMATICAMENTE PARA A FILIAL DESTINO CONFIGURADA PARA ESSE PROCESSO. (CONFIGURADA NA TELA DE MOTIVO).</td></tr>
<tr><td class="ce">FORÇAR FECHAMENTO DE CAIXA</td><td class="cd">IMPOSSIBILITA A ABERTURA OU REABERTURA DO CAIXA COM DATA DIFERENTE DO COMPUTADOR.</td></tr>
<tr><td class="ce">ATIVAR RFID</td><td class="cd">PERMITE O USO DE EMISSÃO DE ETIQUETAS E EFETUAR OPERAÇÕES COM RFID.</td></tr>
<tr><td class="ce">VALOR DE VALE ABATE DO TOTAL DE VENDAS</td><td class="cd">VALOR DO VALE GERADO NA TROCA DE PRODUTOS, NÃO VAI APARECER NO TOTAL DE VENDA.</td></tr>
<tr><td class="ce">DISTRIBUIÇÃO ALTERA ESTOQUE APÓS RECEBIMENTO</td><td class="cd">O SALDO DA DISTRIBUIÇÃO SÓ ENTRARÁ NO ESTOQUE DAS FILIAIS APÓS A CONFIRMAÇÃO DE RECEBIMENTO.</td></tr>
<tr><td class="ce">NÃO INSERIR SERVIÇOS NA NFC-E</td><td class="cd">EMITE UMA NOTA DE SERVIÇO COM OS “ITENS SERVIÇOS” SEPARADOS DA NFC-E</td></tr>
<tr><td class="ce">IMPRIMIR RESUMO NA VENDA</td><td class="cd">IMPRIME DUAS VIAS DE UM RESUMO DA VENDA CONTENDO OS PRODUTOS LANÇADOS, ESSA FERRAMENTA É UTILIZADA PARA PREPARAÇÃO DE PEDIDOS. (EX. CLIENTES FAST FOOD).</td></tr>
<tr><td class="ce">SEPARAR NFCE POR FORNECEDOR</td><td class="cd">EMITE UMA NFCE SEPARADA PARA CADA FORNECEDOR DOS PRODUTOS NA VENDA. PARA HABILITA-LÁ É PRECISO QUE NO CADASTRO DE PRODUTOS ESTEJA CONTENDO O FORNECEDOR E O MESMO CADASTRADO COMO FILIAL DE MESMO NOME COM AS INFORMAÇÕES FISCAIS.</td></tr>
<tr><td class="ce">CONSULTAR ITENS DE VENDA VIA WEBSERVICE</td><td class="cd">TESTEI E NAO IDENTIFIQUEI (NÃO FOI POSSIVEL SABER EM QUE FERRAMENTA DO SISTEMA A REGRA É ATIVADA A REGRA)</td></tr>
<tr><td class="ce">EXPORTAR SALDOS PARA A MATRIZ FRANQUIA</td><td class="cd">FRANQUEADORA PODE EXPORTAR SALDOS DE VARIAS MANEIRAS PARA O  ESTOQUE DA MATRIZ FRANQUIA.</td></tr>
<tr><td class="ce">CONTROLE DE SALDO DO CAIXA</td><td class="cd">TESTEI E NAO IDENTIFIQUEI (NA TELA DE CAIXA DESPESAS ONDE CONTROLAMOS O SALDO DO CAIXA, NAO HOUVE MUDANÇAS)</td></tr>
<tr><td class="ce">OPTAR TIPO DE VENDA</td><td class="cd">AO HABILITAR PERMITE REALIZAR ORÇAMENTO NA TELA DE VENDA.</td></tr>
<tr><td class="ce">HABILITAR EXCLUSÃO GERENCIAL DE VENDA NFCE</td><td class="cd">HABILITA A EXCLUSÃO DE VENDAS NFCE APÓS 30 MINUTOS (SOMENTE GERENCIAL).</td></tr>
<tr><td class="ce">DESATIVAR CAIXA AS CEGAS EM MOVIMENTOS FINALIZADOS</td><td class="cd">DESATIVA O CAIXA AS CEGAS EM RELATÓRIOS DE MOVIMENTOS ANTERIORES JÁ FINALIZADOS. SENDO ASSIM, O USUARIO PODE VER OS RELATORIOS OS MOVIMENTOS ANTERIORES.</td></tr>
<tr><td class="ce">CONSIDERAR CONFIG. FECHAMENTO DE PREVENDA PARA ECF</td><td class="cd">NÃO FOI POSSIVEL TESTAR (NECESSITA ECF )</td></tr>
<tr><td class="ce">INCLUIR/ALTERAR VENDEDORES SÓ NA FRANQUEADORA</td><td class="cd">A INCLUSAO OU ALTERAÇÃO CADASTRO DE VENDEDORES, SÓ SERA FEITO NA MATRIZ FRANQUEADORA. ESSAS INFORMAÇÕES SAO CADASTRADAS EM FUNCIONARIOS TAMBEM.</td></tr>
<tr><td class="ce">HABILITAR CATEGORIA NA REFERÊNCIA</td><td class="cd">HABILITANDO A REGRA, SERÁ POSSÍVEL INFORMAR AS CATEGORIAS NAS REFERÊNCIAS. POSSIBILITANDO A UTILIZAÇÃO NA PARTE DE VENDAS.</td></tr>
<tr><td class="ce">OUTROS SOMENTE COM RETIRADA FUNCIONÁRIO</td><td class="cd">SÓ PODE USAR A FORMA DE PAGAMENTO OUTROS, SE MARCAR RETIRADA DE FUNCIONARIO</td></tr>
<tr><td class="ce">HABILITA CONFERENCIA DE PREVENDA</td><td class="cd">TESTEI E NAO IDENTIFIQUEI (A PRE VENDA FICA EM ANALISE POREM NÃO IDENTIFIQUEI O LOCAL PARA CONFERENCIA)</td></tr>
<tr><td class="ce">DESABILITAR SOMA DO CAIXA/DESPESA COM O DINHEIRO</td><td class="cd">DESABILITA SOMA DO CAIXA/DESPESA COM O DINHEIRO NO RELATÓRIO DE FECHAMENTO AS CEGAS.</td></tr>
<tr><td class="ce">RELATÓRIO VENDA PRODUTOS MOVIMENTO ANTERIOR</td><td class="cd">AO HABILITAR É GERADO UM RELATORIO DO MOVIMENTO ANTERIOR AO ABRIR O MODULO DE VENDA</td></tr>
<tr><td class="ce">TRABALHA SOMENTE COM PLANOS DE PAGAMENTO VISIVEIS</td><td class="cd">PERMITE QUE O SISTEMA MOSTRE AS FORMAS DE PAGAMENTOS "MARCADAS COMO VISIVEIS" NA TELA DE VENDA. NA RETAGUARDA - CADASTRO GERAL - PLANOS DE PAGAMENTOS - MARCAR "COMO VISIVEL" DENTRO DA FORMA DE PAGAMENTO.</td></tr>
<tr><td class="ce">EXCLUIR VARIOS ITENS NA VENDA</td><td class="cd">AO INVES DE EXCLUIR ITEM A ITEM, ESTA REGRA PERMITE SELECIONAR MAIS DE UM ITEM NA VENDA PARA EXCLUSÃO USANDO O "F7".</td></tr>
<tr><td class="ce">NÃO GERAR NFE DE DEVOLUÇÃO A PARTIR DE NOTA MANUAL</td><td class="cd">NOTAS FISCAIS DE DEVOLUÇÃO NÃO SERÃO MAIS GERADAS AO FINAL DE VENDAS TIPO NOTA MANUAL.</td></tr>
<tr><td class="ce">NÃO GERAR BÔNUS APLICANDO DESCONTO MANUAL.</td><td class="cd">VÁLIDO PARA BÔNUS QUE GERAM NA VENDA CASHBACK E PROGRESSIVO, USANDO O DESONTO MANUAL NO MOMENTO DA VENDA.</td></tr>
<tr><td class="ce">GERAR BÔNUS PARA PRODUTOS FORA DE PROMOÇÃO</td><td class="cd">VÁLIDO PARA BÔNUS QUE SÃO GERADOS DA VENDA, PROGRESSIVO E CASHBACK, O VALOR MÍNIMO QUE É  GERARADO  O BÔNUS SERÁ DOS PRODUTOS SEM PROMOÇÃO.</td></tr>
<tr><td class="ce">UTILIZA DEPENDENTES NO CADASTRO DE CLIENTE</td><td class="cd">HABILITA A ABA “DEPENDENTES” NO CADASTRO DE CLIENTES. SERÁ NECESSÁRIO CADASTRAR O ‘PARENTESCO’ NA TELA DE CADASTRO GERAL, OPÇÃO “CADASTRO DE PARENTESCO”. NÃO HABILITADO NA TELA DE CADASTRO DE CLIENTE REDUZIDO.</td></tr>
<tr><td class="ce">LOGO DA REDE A PARTIR DO DIRETÓRIO DE FOTOS</td><td class="cd">AO HABILITAR ESSA REGRA, SERÁ NECESSARIO CRIAR UMA PASTA NO DIRETORIO (C:\Fotos) E COLOCAR A LOGO EM JPG, DESCRIÇÃO LOGO. </td></tr>
<tr><td class="ce">PERGUNTAR SE DESEJA IMPRIMIR CUPOM DE NFC-E</td><td class="cd">A REGRA POSSIBILITA QUE O CLIENTE DECIDA SE SERÁ IMPRESSO O CUPOM DA NFC-E AO FINALIZAR A VENDA.</td></tr>
<tr><td class="ce">TRABALHA COM CONFERÊNCIA DE PEDIDO DE VENDA</td><td class="cd">AO CADASTRAR A NOTA FISCAL, O SISTEMA CARREGARÁ APENAS O PEDIDO QUE FOI FEITA A CONFERÊNCIA.</td></tr>
<tr><td class="ce">NÃO ARMAZENAR HISTÓRICO DE PREÇO</td><td class="cd">AO HABILITAR ESSA REGRA, O SISTEMA NÃO SALVA AS ALTERAÇÕES DE PREÇO DO PRODUTO.</td></tr>
<tr><td class="ce">INFORMAR O PRODUTO NEGATIVO NA VENDA</td><td class="cd">NO MOMENTO DA VENDA, SE CASO A FILIAL ESTEJA CONFIGURADA PARA TRABALHAR COM ESTOQUE NEGATIVO, EXIBE A MENSAGEM INFORMANDO QUE O PRODUTO ESTÁ COM ESTOQUE NEGATIVO.</td></tr>
<tr><td class="ce">TRAB. COM REQUISIÇÃO DE PED. DE COMPRA</td><td class="cd">NÃO FOI POSSIVEL TESTAR ( NECESSITA MATRIZ E LOJA UNIFICADAS EM NUVEM)</td></tr>
<tr><td class="ce">VERIFICAR PARCELA NA BAIXA DE CREDIÁRIO</td><td class="cd">SOMENTE É POSSÍVEL BAIXAR A PARCELA DE UM CONTRATO DE CREDIÁRIO SE A PARCELA ANTERIOR ESTIVER BAIXADA.</td></tr>
<tr><td class="ce">TRABALHA COM PROMOÇÃO SELLBIE</td><td class="cd">UTILIZA A API DA SELLBIE (MOTOR DE PROMOÇÃO) PARA GERAR DESCONTOS PRÉ-DEFINIDOS.</td></tr>
<tr><td class="ce">PEDIDO DE ENTREGA NA TELA DE VENDAS</td><td class="cd">HABILITA O PEDIDO DE ENTREGA NA TELA PADRÃO DE VENDA</td></tr>
<tr><td class="ce">HABILITAR CLASSIFICAÇÃO DE CLIENTE</td><td class="cd">HABILITA O CAMPO CLASSIFICAÇÃO DENTRO DO CADASTRO DO CLIENTE.</td></tr>
<tr><td class="ce">ANALISE DE PEDIDO COM FILIAL CENTRALIZADA</td><td class="cd">ANALISE DOS PEDIDOS DE UMA FILIAL PRINCIPAL, LA NO PDVANALISE - ANALISE DE PEDIDOS.</td></tr>
<tr><td class="ce">NÃO ENVIAR CPF NA NFCE</td><td class="cd">QUANDO ATIVADO, NÃO ENVIA O CPF NO CUPOM DO NFCE</td></tr>
<tr><td class="ce">NÃO SEPARAR ITENS NA PROMOÇÃO PARA VÁRIAS PEÇAS</td><td class="cd">TESTEI E NÃO IDENTIFIQUEI (TESTEI COM A PROMOÇÃO INDICADA POREM NÃO VISUALIZEI DIFERENÇA)</td></tr>
<tr><td class="ce">TRABALHA COM CUSTOMIZACAO DE CAMISAS</td><td class="cd">HABILITA A MÁSCARA DE CÓDIGO "REF_FORNECEDOR#NOME"</td></tr>
<tr><td class="ce">HABILITA FILIAÇÃO NO CADASTRO DE CLIENTE</td><td class="cd">"AO HABILITAR ESSA FUNÇÃO, O SISTEMA HABILITA NO CADASTRO DE CLIENTE A FILIAÇÃO ( FILHO OU FILHA ).
"</td></tr>
<tr><td class="ce">GERAR NOTA PELO DOC DA VENDA SÓ COM VALOR LÍQUIDO</td><td class="cd">HABILITANDO ESSA REGRA, AO DAR DESCONTO NO ITEM NA VENDA E LANÇAR O DOC DA VENDA NO CADASTRO DA NFE, O SISTEMA TRAS SOMENTE O VALOR LIQUIDO DO PRODUTO QUE FOI DADO DESCONTO NO ATO DA VENDA. O VALOR REAL SEM DESCONTO DO PRODUTO, NAO APARECE NO CADASTRO DA NFE.</td></tr>
<tr><td class="ce">LOJA VISUALIZA SOMENTE SUAS COMPRAS NO CLIENTE</td><td class="cd">SISTEMA PERMITE QUE A LOJA SÓ VISUALIZE A SUA PROPRIA VENDA DENTRO DO CADASTRO DO CLIENTE. REGRA APLICADA PARA BANCO DE DADOS UNICO.</td></tr>
<tr><td class="ce">HABILITAR Nº DA NOTA NA VENDA POR NOTA MANUAL</td><td class="cd">HABILITA UM CAMPO 'NOTA' QUE APARECE NA ULTIMA TELA DO PROCESSO DA VENDA, PARA DIGITAR UM NUMERO DE NOTA MANUAL PARA CONTROLE PESSOAL.</td></tr>
<tr><td class="ce">TRABALHA COM INTEGRAÇÃO LUXOTTICA</td><td class="cd">NÃO FOI POSSIVEL TESTAR (NECESSITA LUXOTTICA)</td></tr>
<tr><td class="ce">TRABALHA COM DELIVERY</td><td class="cd">AO ATIVAR, IRÁ HABILITAR OPÇÕES DE DELIVERY NA TELA DE VENDAS.</td></tr>
<tr><td class="ce">ENVIAR ENDEREÇO DO DESTINATÁRIO NA NFCE</td><td class="cd">FORÇA O ENVIO DE ENDEREÇO DO DESTINATÁRIO NA NFCE INDEPENDENTE DO VALOR.</td></tr>
<tr><td class="ce">INFORMAR QUANTIDADE DE PARCELAS DO CHEQUE NA VENDA</td><td class="cd">INFORMAR QUANTIDADE DE PARCELAS DO CHEGUE IGUAL NA FUNÇÃO 'CREDITO'. FUNCIONA SOMENTE COM A REGRA 33(TRABALHA COM PLANOS DE PAGAMENTO) ATIVADA.</td></tr>
<tr><td class="ce">BLOQUEAR FUNÇÃO F3</td><td class="cd">BLOQUEIA A UTILIZAÇÃO DO F3 NA TELA DE VENDA E PRE-VENDA.</td></tr>
<tr><td class="ce">	TRABALHA COM OUTROS TIPOS DE ESTOQUE PADRÃO</td><td class="cd">AO HABILITAR ESSA REGRA, AO DAR (SAIDA) AVULSA DE PRODUTOS, O SISTEMA AVISA CASO O ITEM DE SAIDA ESTEJA ABAIXO DO MINIMO CADASTRADO NO (ESTOQUE PADRÃO). E ABRE A TELA DE VISUALIZAÇÃO DO ITEM ABAIXO DO MINIMO.</td></tr>
<tr><td class="ce">	TRABALHA COM ESTOQUE RESERVADO PEDIDO DE VENDA</td><td class="cd">REGRA HABILITADA,  RESERVA ITENS PARA O PEDIDO DE VENDA NA CRIAÇÃO OU ALTERACAO DO PEDIDO.</td></tr>
<tr><td class="ce">	TRABALHA COM INTEGRAÇÃO COM TRANSPORTADORAS</td><td class="cd">HABILITA TELA DE INTEGRAÇÃO COM TRANSPORTADORA.</td></tr>
<tr><td class="ce">	HABILITAR CONTIGENCIA OFFLINE</td><td class="cd">AO HABILITAR, O SISTEMA CONFIGURA A NF EM MODO DE CONTIGENCIA. SENDO ASSIM, NA SEFAZ ESSA NF FICA DE FATO EM CONTIGENCIA EM SEU BANCO DE DADOS. (EX. CLIENTE PRECISA EMITIR NOTAS EM HOMOLOGAÇÃO PARA COMEÇAR A EMITIR AS NF EM PRODUÇÃO.)</td></tr>
<tr><td class="ce">	VENDEDOR POR ITEM DA VENDA</td><td class="cd">"AO ATIVAR, SERÁ POSSÍVEL SELECIONAR VENDEDOR AO LANÇAR CADA PRODUTO EM UMA VENDA, CASO NÃO APAREÇA, EXECUTAR UM RECURSO EM MANUTENÇÃO DE TABELAS, NA ABA Outros(Novo) - Atualizar vendedor	 Atualizar vendedores na venda	Atualizar registro de vendedor da tabela caixa para tabela vendas ""EXECUTAR"" - PARA ATUALIZAR ESSE CAMPO"</td></tr>
</table>
	</div>
</div>
</div>
</section>